### ISSUE TITLE
Chat went blank with this script on

### ISSUE THREAD

**Issue by slikie** [valera5505/twitch-pip-button#1]
Hi valera, great work with this script.
However after installing this the chat went completely blank.
Please fix this:)

**Comment by valery-kirichenko** [comment]
Can't repeat. Could you send screenshot? Also what extensions do you use on twitch, and your OS version?

**Comment by slikie** [comment]
Thank you for the rapid respond and I'm sorry for not preparing the specs for issue.
I'm on 10.13 Beta. Probably that's the problem. But the PIP works fine so I'm confusing...
Here's the screenshot.
![screen shot 2017-07-16 at 9 53 30 pm](https://user-images.githubusercontent.com/13197246/28248115-718fdd88-6a04-11e7-931e-1fc1341b8dcb.png)
![screen shot 2017-07-16 at 10 06 47 pm](https://user-images.githubusercontent.com/13197246/28248213-510533a4-6a06-11e7-81bf-2fcb4d9eff91.png)


After disabling all other extensions and user scripts it repeats under  private window.

In developer console there's several errors.

`
[Error] TypeError: undefined is not an object (evaluating 'e.style')

[Error] TypeError: undefined is not an object (evaluating 'lnk.innerHTML = ""')
	ss (Script Element 1:1:93)

[Error] TypeError: undefined is not an object (evaluating 'lnk.innerHTML = ""')
	ss (Script Element 1:1:93)

[Error] NotFoundError (DOM Exception 8): The object can not be found here.
	removeChild (global-a53aabea5b0fea140eb5990748487b60.js:11:14409)
	o (global-a53aabea5b0fea140eb5990748487b60.js:11:14409)

[Error] NotFoundError (DOM Exception 8): The object can not be found here.
	removeChild (player.js:23:1000)
	i (player.js:23:1000)

[Error] TypeError: undefined is not an object (evaluating 'lnk.innerHTML = ""')
	ss (Script Element 1:1:93)

[Error] TypeError: undefined is not an object (evaluating 'lnk.innerHTML = ""')
	ss (Script Element 2:1:93)

[Error] TypeError: undefined is not an object (evaluating 'lnk.innerHTML = ""')
	ss (Script Element 1:1:93)
`

**Comment by valery-kirichenko** [comment]
That's strange. Really what my script doing is it loads icon and appends button to player. But this errors are from Twitch scripts. I also use 10.13 beta, but everything works fine.

**Comment by slikie** [comment]
Sorry I'm still learning how to use git and  maybe have produced lots of spam emails XD

I just found out I have issue accessing rawgit.com so the css never got downloaded.
I meant to test it on my fork but accidentally create a pull request........
I can't apologize  enough for wasting your precious time.
